name: native_pdf_view
description: Flutter plugin to render PDF files on Web, MacOS, Android and iOS.
version: 3.8.0
homepage: https://github.com/rbcprolabs/packages.flutter/tree/master/packages/native_pdf_view

environment:
  sdk: '>=2.7.0 <3.0.0'
  flutter: '>=1.17.0 <2.0.0'

dependencies:
  flutter:
    sdk: flutter
  extended_image: ^5.1.2
  synchronized: ^3.0.0
  device_info: ^2.0.2
  native_pdf_renderer: 
    git: 
      url: git@github.com:manabie-com/packages.flutter.git
      path: packages/native_pdf_renderer
      ref: native_pdf_renderer-v1.6.2
      
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1
